USE ships;

--1--

SELECT COUNT(*) AS CountClassesBB
FROM CLASSES
WHERE TYPE='bb';

--2--

SELECT CLASS, AVG(NUMGUNS)
FROM CLASSES
WHERE TYPE='bb'
GROUP BY CLASS;

--3--

SELECT  AVG(NUMGUNS) AS avgGuns
FROM CLASSES
WHERE TYPE='bb'

--4--

SELECT CLASS, MIN(LAUNCHED) AS FirstYear, MAX(LAUNCHED) AS LastYear
FROM SHIPS
GROUP BY CLASS;

--5--

SELECT CLASS, COUNT(*) AS No_Sunk
FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP=SHIPS.NAME
WHERE RESULT='sunk'
GROUP BY CLASS;

--6--
SELECT CLASS, COUNT(*) AS NO_Sunk
FROM SHIPS AS sh
JOIN OUTCOMES AS o ON sh.NAME = o.SHIP
WHERE RESULT = 'sunk'
GROUP BY CLASS
HAVING CLASS IN (SELECT c.CLASS
				 FROM CLASSES AS c
				 JOIN SHIPS AS sh ON sh.CLASS = c.CLASS
				 GROUP BY c.CLASS
				 HAVING COUNT(sh.NAME) > 2);

--7--

SELECT *
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS
GROUP BY COUNTRY
