USE movies;

--1--

SELECT TITLE,YEAR,LENGTH
FROM MOVIE
WHERE LENGTH>120 OR LENGTH IS NULL AND YEAR<2000 ;

--2--

SELECT NAME,GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND BIRTHDATE>1948
ORDER BY NAME DESC;

--3--

SELECT STUDIONAME,COUNT(DISTINCT STARNAME) AS actors
FROM MOVIE JOIN STARSIN ON MOVIE.TITLE=STARSIN.MOVIETITLE
GROUP BY STUDIONAME;

--4--

SELECT STARNAME,COUNT(DISTINCT MOVIETITLE) AS movies
FROM STARSIN
GROUP BY STARNAME;

--5--

SELECT STUDIONAME,TITLE,YEAR
FROM MOVIE AS m
WHERE TITLE = 
(SELECT TOP(1)  TITLE
FROM MOVIE
WHERE STUDIONAME=m.STUDIONAME
ORDER BY YEAR DESC
)
ORDER BY YEAR DESC;

--6--

SELECT TOP(1) NAME
FROM MOVIESTAR AS m
WHERE GENDER='M' AND BIRTHDATE =
(SELECT TOP(1) BIRTHDATE
FROM MOVIESTAR
WHERE NAME=m.NAME
ORDER BY BIRTHDATE);

SELECT TOP(1) NAME
FROM MOVIESTAR 
WHERE GENDER='M'
ORDER BY BIRTHDATE DESC;

--7--

SELECT m.STUDIONAME,n.STARNAME,COUNT(n.STARNAME) AS movies
FROM MOVIE as m JOIN STARSIN AS n ON m.TITLE=n.MOVIETITLE
GROUP BY STUDIONAME,STARNAME
HAVING COUNT(n.STARNAME)>= ALL 
(SELECT COUNT(STARNAME)
FROM STARSIN 
GROUP BY STARNAME
)

--8--

SELECT MOVIETITLE,YEAR,COUNT(STARNAME) AS actors
FROM MOVIE as m JOIN STARSIN AS n ON m.TITLE=n.MOVIETITLE
GROUP BY MOVIETITLE,YEAR
HAVING COUNT(n.STARNAME) IN
(SELECT COUNT(STARNAME)
FROM STARSIN 
GROUP BY MOVIETITLE
HAVING COUNT(STARNAME)>2
)

