USE ships;

--1--

SELECT DISTINCT SHIP
FROM OUTCOMES 
WHERE SHIP LIKE '[CK]%';

--2--

SELECT DISTINCT NAME,COUNTRY
FROM SHIPS LEFT JOIN CLASSES ON CLASSES.CLASS=SHIPS.CLASS
left JOIN OUTCOMES ON OUTCOMES.SHIP=SHIPS.NAME
WHERE RESULT!='sunk' OR RESULT is null;

--3--

SELECT DISTINCT COUNTRY,count(RESULT)
FROM SHIPS RIGHT JOIN CLASSES ON CLASSES.CLASS=SHIPS.CLASS
left JOIN OUTCOMES ON OUTCOMES.SHIP=SHIPS.NAME
WHERE RESULT='sunk' OR RESULT is null
GROUP BY COUNTRY;

--4--

SELECT BATTLE
FROM OUTCOMES as o1
GROUP BY BATTLE
HAVING COUNT(BATTLE)>ANY
(SELECT COUNT(BATTLE)
FROM OUTCOMES 
WHERE BATTLE='Guadalcanal')

--5--

SELECT BATTLE
FROM OUTCOMES as o1
GROUP BY BATTLE
HAVING COUNT(BATTLE)>ANY
(SELECT COUNT(BATTLE)
FROM OUTCOMES 
WHERE BATTLE='Surigao Strait')

--6--

SELECT DISTINCT NAME
FROM CLASSES JOIN SHIPS ON SHIPS.CLASS=CLASSES.CLASS
WHERE DISPLACEMENT<=ALL
(SELECT DISPLACEMENT
FROM CLASSES) AND
NUMGUNS>=ANY
(SELECT NUMGUNS
FROM CLASSES)

--7--

SELECT COUNT(*) AS Num
FROM OUTCOMES AS O JOIN OUTCOMES AS U ON O.SHIP=U.SHIP
WHERE O.RESULT='damaged' and U.RESULT='ok'

--8--

SELECT O.SHIP
FROM OUTCOMES AS O JOIN OUTCOMES AS U ON O.SHIP=U.SHIP
WHERE O.RESULT='damaged' and U.RESULT='ok' 
GROUP BY O.BATTLE,O.SHIP
HAVING COUNT(O.SHIP)<=COUNT(U.SHIP);

