USE movies;

--1--

SELECT TITLE,NAME
FROM MOVIE JOIN MOVIEEXEC ON PRODUCERC#=CERT#
WHERE PRODUCERC# IN
(SELECT PRODUCERC#
FROM MOVIE
WHERE TITLE='Star Wars');

--2--

SELECT DISTINCT NAME
FROM MOVIE JOIN MOVIEEXEC ON PRODUCERC#=CERT#
WHERE TITLE IN
(SELECT MOVIETITLE
FROM STARSIN
WHERE STARNAME='Harrison Ford');

--3--

SELECT DISTINCT STUDIONAME,STARNAME
FROM MOVIE JOIN STARSIN ON YEAR=MOVIEYEAR
ORDER BY STUDIONAME;

--4--

SELECT DISTINCT STARNAME,NETWORTH,TITLE
FROM (MOVIE JOIN MOVIEEXEC ON CERT#=PRODUCERC#) JOIN STARSIN ON TITLE=MOVIETITLE
WHERE NETWORTH >=ALL
(SELECT NETWORTH
FROM MOVIEEXEC)
ORDER BY TITLE;

--5--

SELECT DISTINCT NAME,MOVIETITLE
FROM MOVIESTAR LEFT JOIN STARSIN ON NAME=STARNAME
WHERE MOVIETITLE is null;

