USE ships;

--1--

SELECT *
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS

--2--

SELECT *
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
ORDER BY NAME;

--3--

SELECT DISTINCT COUNTRY,NAME
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
WHERE NAME NOT IN
(SELECT SHIP
FROM OUTCOMES)
ORDER BY COUNTRY;

--4--

SELECT DISTINCT NAME as 'Ship Name'
FROM CLASSES JOIN SHIPS ON SHIPS.CLASS=CLASSES.CLASS
WHERE NUMGUNS>=7 AND LAUNCHED=1916;

--5--

SELECT DISTINCT SHIP,BATTLE,DATE
FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE=BATTLES.NAME
WHERE RESULT='sunk'
ORDER BY BATTLE;

--6--

SELECT DISTINCT NAME,DISPLACEMENT,LAUNCHED
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS
WHERE NAME=CLASSES.CLASS
ORDER BY NAME;

--7--

SELECT DISTINCT *
FROM CLASSES
WHERE CLASS NOT IN
(SELECT CLASS
FROM SHIPS);

--8--

SELECT DISTINCT NAME,DISPLACEMENT,NUMGUNS,RESULT
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
JOIN CLASSES ON CLASSES.CLASS=ships.CLASS
WHERE BATTLE='North Atlantic';
