USE ships;

--1--

SELECT DISTINCT NAME
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS
WHERE DISPLACEMENT>50000;

--2--

SELECT DISTINCT NAME,DISPLACEMENT,NUMGUNS
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS
WHERE NAME=ANY
(SELECT DISTINCT NAME
FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP=SHIPS.NAME 
WHERE BATTLE='Guadalcanal');

--3--

SELECT DISTINCT c1.COUNTRY
FROM CLASSES AS c1 JOIN CLASSES AS c2 ON c1.TYPE!=c2.TYPE
WHERE  c1.TYPE='bc' AND c2.TYPE='bb' AND c1.COUNTRY=c2.COUNTRY;

--4--

SELECT outc1.SHIP
FROM OUTCOMES AS outc1 JOIN OUTCOMES AS outc2 ON outc1.SHIP=outc2.SHIP
JOIN BATTLES AS b1 ON b1.NAME=outc1.BATTLE
JOIN BATTLES AS b2 ON b2.NAME=outc2.BATTLE
WHERE outc1.RESULT='damaged' AND b1.DATE<b2.DATE; 
