USE movies;

--1--

SELECT MOVIEEXEC.NAME
FROM MOVIESTAR JOIN MOVIEEXEC 
ON MOVIESTAR.NAME=MOVIEEXEC.NAME
WHERE GENDER='F' AND NETWORTH>10000000;

--2--

SELECT DISTINCT MOVIESTAR.NAME
FROM MOVIESTAR JOIN MOVIEEXEC 
ON MOVIESTAR.NAME!=MOVIEEXEC.NAME

--3--

SELECT DISTINCT TITLE
FROM MOVIE 
WHERE LENGTH >
(SELECT LENGTH
FROM MOVIE
WHERE TITLE='Star Wars');

--4--

SELECT DISTINCT TITLE ,NAME
FROM MOVIEEXEC JOIN MOVIE ON CERT#=PRODUCERC#
WHERE NETWORTH >
(SELECT NETWORTH
FROM MOVIEEXEC
WHERE NAME='Merv Griffin');