USE ships;

--1--

SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS>=ALL
(SELECT NUMGUNS
FROM CLASSES);

--2--

SELECT DISTINCT CLASS
FROM SHIPS JOIN OUTCOMES ON SHIP=NAME
WHERE RESULT='sunk';

--3--

SELECT DISTINCT NAME,SHIPS.CLASS
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
WHERE BORE=16;

--4--

SELECT DISTINCT BATTLE
FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP=SHIPS.NAME
WHERE CLASS='Kongo';

--5--

SELECT DISTINCT CLASS,NAME
FROM SHIPS 
WHERE CLASS IN
(SELECT CLASS
FROM CLASSES AS c
WHERE c.NUMGUNS>=ALL 
(SELECT NUMGUNS
FROM CLASSES
WHERE BORE=c.BORE))
ORDER BY CLASS;